function USjhData11Apr2020 = USimportfile(filename)

    %IMPORTFILE Import numeric data from a text file as a matrix.
    %   USJHDATA11APR2020 = IMPORTFILE(FILENAME) Reads data from text file
    %   FILENAME for the default selection.
    %
    %   USJHDATA11APR2020 = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
    %   from rows STARTROW through ENDROW of text file FILENAME.
    %
    % Example:
    %   USjhData11Apr2020 = importfile('US-jhData-11-Apr-2020.CSV', 2, 3254);
    %
    %    See also TEXTSCAN.

    % Auto-generated by MATLAB on 2020/04/11 17:07:41

    %% Initialize variables.
    delimiter = ',';
    if nargin<=2
        startRow = 2;
        endRow = inf;
    end

    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: text (%q)
    %   column3: text (%q)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: text (%q)
    %   column7: text (%q)
    %	column8: text (%q)
    %   column9: double (%f)
    %	column10: double (%f)
    %   column11: text (%q)
    %	column12: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%q%q%f%f%q%q%q%f%f%q%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Create output variable
    dataArray([1, 4, 5, 9, 10, 12]) = cellfun(@(x) num2cell(x), dataArray([1, 4, 5, 9, 10, 12]), 'UniformOutput', false);
    USjhData11Apr2020 = [dataArray{1:end-1}];

end